### ISSUE TITLE
RuntimeError: expected flip dims axis >= 0, but got min flip dims=-1

### ISSUE THREAD

**Issue by zhouyuangan** [anibali/dsntnn#12]
My torch version is 0.4.1, an error occurs when I ran  [basic usage guide](https://github.com/anibali/dsntnn/blob/master/examples/basic_usage.md).

I had tried to pip install another dsntnn version described at #6, looking for your reply as soon as possible.

```Traceback (most recent call last):
  File ".\model.py", line 71, in <module>
    coords, heatmaps = model(t)
  File "C:\Python35\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File ".\model.py", line 46, in forward
    coords = dsntnn.dsnt(heatmaps)
  File "C:\Python35\lib\site-packages\dsntnn\__init__.py", line 79, in dsnt
    return soft_argmax(heatmaps)
  File "C:\Python35\lib\site-packages\dsntnn\__init__.py", line 67, in soft_argmax
    return linear_expectation(heatmaps, values).flip(-1)
RuntimeError: expected flip dims axis >= 0, but got min flip dims=-1```

**Comment by zhouyuangan** [comment]
I found flip(-1) is not support for version 0.4.1 in this [lik](https://github.com/pytorch/pytorch/issues/17204) which I have checked on. So finally I install dsntnn==0.3.0 instead of 0.4.0.
